<h1>Reports generated by District NRDMS Centre, Bangalore Rural</h1>
<h2>&nbsp;</h2>
<ul>
	<li class="gap-above-small"><a href="<?=RESOURCES_URL?>Data_Dict.pdf" target="_blank">Data Dictionary of Bangalore Rural District</a></li>
	<li class="gap-above-small"><a href="<?=RESOURCES_URL?>Water_Report.pdf" target="_blank">Report on Spatial Representation of Villages which are Facing Acute Water Problems in Bangalore Rural District</a></li>
	<li class="gap-above-small"><a href="<?=RESOURCES_URL?>Zpcons_Report.pdf" target="_blank">Zilla Panchayat Constituencies - A GIS Approach Mapping</a></li>
</ul>
