<h1>Patent Information Centre</h1>
<h2>&nbsp;</h2>
<h3 id="Patent_Awareness_Programme_at_Gulbarga">Patent Awareness Programme at Gulbarga</h3>
<p>The first patent awareness programme was organized at PDA College of Engineering, Gulbarga on 23rd September 2005. Several people from industry, Gulbarga University, University of Veterinary and Animal Husbandry (Bidar), University of Agricultural Sciences, Karnataka Power Corporation, medical colleges, engineering colleges located around Gulbarga and neighbouring districts were invited to participate in this programme. About 200 persons participated in the programme.</p>
<p>Dr V. D. Mytri, Principal, PDA College of Engineering, welcomed the dignitaries and the participants. The programme was inaugurated by the Chief Guest, Shri S J Vaidya, Asst. Controller, Patent office, Mumbai. In his speech, he stressed the need for registering patents and explained the utilities of such activity. The Guest of Honour, Prof. Patil, Dean, Gulbarga University spoke about how inventors in the past had helped technological and social development. Shri Ramakanth Nidgurgi, Secretary of Hyderabad Karnataka Chamber of Commerce and Industries, spoke about how inventions could help to boost economic and technological developments in the country. Shri Baburao Mungane, Member, Governing Council, PDA college, presided over the function. He explained how patents can also registered and assigned just the same way as any other immovable property and stressed its importance in the light of new agreements such as TRIPS and WTO.</p>
<p>The first technical session was chaired by Prof. J. S. Patil. Shri Yashawant Panwar, TIFAC, spoke on the patents and various forms of patents that can be registered in India and also on other forms of IPRs like copyright, trade mark, geographical indications, etc. He gave many examples of how very simple inventions (like safety pins, post-it etc) gave the people advantage in their daily lives and also benefited the inventor financially. Shri Surya Senthil, Head, Technology Law Division, Surana Surana International Attorneys, Chennai, spoke on "Novelty and Non-obviousness in Patents". This was followed by a question-answer session.</p>
<p>Shri Yashawant Panwar, TIFAC, chaired the second technical session. Shri Vaidya, spoke on patenting in India with relevant details like fee structure, time required etc and also on how to obtain patent in other countries. Shri K Subodh Kumar, Technology Cousellor, CII-APTDC, spoke on "Management of Intellectual Property". He explained the importance of policy of patenting giving example of an Australian firm which has patented many power driving equipments. Further, he also explained various steps involved in registering referring the case of Pochampalli Ikat, a case study of traditional saree marketing in Nalgonda district of Andhra Pradesh. This was followed by question-answer session.</p>
<p class="img-with-caption"><img title="Shri Vaidya speaking on the occasion of IPR meeting in Gulbarga on 23rd September 2005." class="img-responsive" style="" src="<?=PUBLIC_URL?>images/stock/patent_Gulbarga.jpg" alt="Shri Vaidya speaking on the occasion of IPR meeting in Gulbarga on 23rd September 2005."/>Shri Vaidya speaking on the occasion of IPR meeting in Gulbarga on 23rd September 2005.</p>
<h3 id="Patent_Awareness_Programme_at_Shimoga">Patent Awareness Programme at Shimoga</h3>
<p>The second Patent Awareness Programme was organized at JNN College of Engineering, Shimoga on 21st December 2005. Several people from industry, Kuvempu University, Law College, University of Agricultural Sciences, engineering and medical colleges located in and around Shimoga were invited to participate in this programme. About 120 people participated in this programme.</p>
<p>Dr A V Subramanyam, Principal, JNN College of Engineering, Shimoga, welcomed the dignitaries and participants. The programme was inaugurated by Shri K. Ravi, General Manager (production), Mysore paper Mills, Bhadravati. Shri G. Nanjundappa, Vice president, National Education Society, Shimoga presided over the function.</p>
<p>During the first technical session, Shri Yashawant Dev Panwar spoke on various forms of Intellectual Property Rights such as Patents, Copyrights, Geographical Indications, Layout Designs, Industrial Designs etc and informed about the characteristics of all types of IPRs and their economic importance. He also informed the advantages of availing patents and other form of IPRs. Shri Abhayan Jawaharlal, Head, Legal Cell, Biocon India Pvt Ltd, spoke extensively on copyright issues and the litigations arising out of the current cyber space problems. Prof. Mohan Ram of Law College, Shimoga, chaired the session and concluded with the remark that it is imperative that patent awareness is created among all technocrats and local level innovators in order to get economic benefit out of inventions and, thereby, help improve economy of the nation.</p>
<p>During second technical session, Shri. C. N. Shashidhara, Patent Examiner, Patent Office, Chennai spoke on the procedures for patenting and patent examination. He informed that patenting procedures are relatively simple and easy now. He also spoke on various laws and resolutions that control patent rights and concessions. Shri Panwar spoke on the aspect of "Novelty in Non-obviousness in Patenting". He also spoke about "Patent Search" and informed about various internet sites available for patent searching. This session was chaired by Prof. Satyamurthy, Principal of Law College, Shiomoga. In his concluding remark, he said that, though late, the regime of patenting has arrived in India and we should take full advantage of the situation.</p>
<p class="img-with-caption"><img title="The Chief Guest Shri K. Ravi, speaking at the inaugural function" class="img-responsive" style="" src="<?=PUBLIC_URL?>images/stock/patent_Shimoga.jpg" alt="The Chief Guest Shri K. Ravi, speaking at the inaugural function"/>The Chief Guest Shri K. Ravi, speaking at the inaugural function</p>
<h3 id="Patent_Awareness_Programme_at_Belgaum">Patent Awareness Programme at Belgaum</h3>
<p>The third Patent Awareness Programme was organized at Gogte Institute of Technology, Belgaum (GIT) on 24th November 2006. Several people from Engineering Colleges, Polytechnics, Law Colleges, Medical Colleges and Industries located in and around Belgaum and neighbouring districts were invited to participate in this programme and about 220 persons participated.</p>
<p>Dr D H Rao, Principal, Gogte Institute of Technology, Belgaum, introduced the dignitaries and welcomed dignitaries and participants. The programme was inaugurated by Shri Sureshan Moothedath, General Manager, Technology &amp; Process (Alumina), Hindustan Aluminum Company, Belgaum and was further followed by keynote address by him. Shri S M Kulkarni, Chairman, Board of Management, Karnatak Law Society, Belgaum presided over the function.</p>
<p>During the first technical session Shri Yashawant Dev Panwar, Scientist, TIFAC, spoke on various forms of Intellectual Property Rights (IPRs) such as patents, copyrights, geographical indications, layout designs, industrial designs etc and informed the advantages of availing a patent or other form of IPRs by quoting various examples like basmati rice etc. He also informed the audience about the characteristics of different types of IPRs and their economic importance. Dr Madhusudan spoke at length about patenting system in India. He gave details about various aspects of patenting like filing patent application, examination of patents, opposition etc. This technical session was chaired by Dr S R Bharamanaikar, Director, Belgaum Institute of Management Studies, Belgaum.</p>
<p>The second technical session consisted of a presentation on "Copyright Management" by Shri Abhayan Jawaharlal, Head Legal, Biocon India Pvt Ltd, Bangalore. He spoke extensively on copyright issues and the litigations arising out of the current cyber space problems. He cited many examples to stress the need for copyrighting. The session was chaired by Dr A B Kalkundrikar, Principal, Gogte College of Commerce, Belgaum. Further, technical sessions were followed by question-answer session. Many questions related to technicalities of patents like patentability of innovations etc and patenting system were posed which were duly clarified by the speakers.</p>
<p class="img-with-caption"><img title="Chief Guest, Shri Sureshan Moothedath addressing the participants" class="img-responsive" style="" src="<?=PUBLIC_URL?>images/stock/patent_Belgaum.jpg" alt="Chief Guest, Shri Sureshan Moothedath addressing the participants"/>Chief Guest, Shri Sureshan Moothedath addressing the participants</p>
<h3 id="Patent_Awareness_Programme_at_Mangalore">Patent Awareness Programme at Mangalore</h3>
<p>The Fourth Patent Awareness Programme was organized at the New Senate Hall, Mangalore University, Mangalagangothri on 8th March 2007. About 195 persons from various institutions attended the programme. The participants included faculty, students from various engineering, law, commerce colleges and polytechnics from Mangalore and other neighbouring districts and people from industries and government departments.</p>
<p>Prof. P. S. Yadapadithaya, Professor and Chairman, Department of Commerce, Mangalore University and coordinator for this programme introduced the dignitaries. Prof. M. K. Surappa, Secretary, KSCST, was the Guest of Honour and he gave a brief introduction of Patent Information Cell at KSCST. The Chief Guest, Mr. R. S. Beerannanavar, District Judge, Labour Court, Mangalore inaugurated the programme. Prof. B. K. Ravindra, Principal, S. D. M. Law College, Mangalore delivered the keynote address. Prof. K. M. Kaveriappa, Vice-Chancellor, Mangalore University, released the book <strong><i>"Bouddhika Aasthi Hakkugalu"</i></strong>, a question-answer booklet in Kannada on IPRs (brought out by KSCST). Prof. K. M. Kaveriappa presided over the function and, in his presidential address, he highlighted the importance of of IPRs in biological products, citing examples of basmati rice, medicinal plants and other research products.</p>
<p>The first technical session consisted of two lectures - "Introduction to IPR and Case Studies" by Mr. Yashawant Dev Panwar, Scientist, TIFAC, New Delhi and "Patenting System in India" by Dr S Punithavathi, Patent Office, Chennai and the session was chaired by Ms. Khadeeja Saleem, Faculty, S. D. M. Law College, Mangalore. In his lecture, Mr. Panwar spoke on different forms of IPRs with suitable examples, with specific reference to patents. Dr. S. Punithavathi explained the present system of patenting in India and also gave necessary details on various steps involved in filing patents (like provisional and final specifications, patent examination, publication, opposition etc), time required for each of the steps and fees to be paid at different stages. The second technical session also consisted of two lectures - "Novelty and Inventiveness in Patents" by Mr. Ravi Bhola, Patent Attorney, K &amp; S Partners and "Copyright Management" by Mr. Abhayan, Head, Legal Cell, Biocon India. This session was chaired by Prof. B. S. Reddy, Principal, R. L. Law College, Davanagere. Mr. Bhola explained why novelty and inventiveness are essential for grant of patents and how these are decided during patent examination. Mr. Abhayan discussed extensively on copyright issues and the litigations arising out of them, with special reference to current cyber space problems. Further, these technical sessions were followed by question-answer session in which questions related to technicalities of patents (like patentability of innovations etc) and patenting procedures were posed by the participants and were duly clarified by the speakers.</p>
<p class="img-with-caption"><img title="The Chief Guest, Mr. R. S. Beerannanavar inaugurating the programme" class="img-responsive" style="" src="<?=PUBLIC_URL?>images/stock/patent_Mangalore.jpg" alt="The Chief Guest, Mr. R. S. Beerannanavar inaugurating the programme"/>The Chief Guest, Mr. R. S. Beerannanavar inaugurating the programme</p>
<h3 id="Patent_Awareness_Programme_at_Hassan">Patent Awareness Programme at Hassan</h3>
<p>The Fifth Patent Awareness Programme was organized at Malnad College of Engineering, (MCE), Hassan on 9th March 2007. About 127 persons from various institutions attended the programme. The participants included faculty, students from various engineering colleges and polytechnics and people from industries and government departments in and around Hassan and neighbouring districts.</p>
<p>Dr. Joseph Gonsalves, Professor, Mechanical Engineering, MCE, Hassan and coordinator for this programme, introduced the dignitaries. The programme was inaugurated by Mr. M. K. Govardhan Kumar, distinguished industrialist from Hassan. Dr. R. Saha, Adviser, Department of Science and Technology and Director, Patent Facilitating Center, TIFAC, New Dehli delivered the keynote address in which he informed about the evolution of patenting system and also explained the importance of IPRs in the present WTO regime. Mr. C. S. Krishna Swamy, Treasurer, Malnad Technical Education Society (MTES) introduced the book <strong><i>"Bouddhika Aasthi Hakkugalu"</i></strong>, a question-answer booklet in Kannada on IPRs (brought out by KSCST). Dr. M. G. Venkateshamurthy, Principal, MCE addressed the gathering and Mr. D. A. Chandre Gowda, Secretary, MTES, presided over the function.</p>
<p>The first technical session consisted of two lectures - "Introduction to IPR and Case Studies" by Dr. R. Saha, adviser, DST and director, PFC-TIFAC, New Delhi and "Patenting System in India" by Dr. A. T. Patre, Patent Office, Mumbai. Dr. Saha spoke on different forms of IPRs with suitable examples, with specific reference to patents. Dr. A. T. Patre explained the present system of patenting in India with details on various steps involved in filing patents (like provisional and final specifications, patent examination, publication, opposition etc), time required for each of the steps and fees to be paid at different stages. He also gave some interesting data patent applications filed, patents granted in various patent offices in India. The second technical session also consisted of two lectures - "Novelty and Inventiveness in Patents" by Mr. Surya Senthil, Patent Attorney, JUS Maxima Law Office, Chennai and "Patent Information and its access" by Mr. Yashawant Dev Panwar, Scientist, TIFAC, New Delhi. Mr. Senthil spoke on how novelty and inventiveness are essential for consideration for granting patents and also how these are decided though exhaustive patent searches. Mr. Panwar gave details of various databases - Indian and foreign, with free and paid access - available for patent searching to establish novelty. Also, he explained how patent search is done using key words and combination of keywords. Further, these technical sessions were followed by question-answer session in which questions related to technicalities of patents (like patentability of innovations etc) and patenting procedures were posed by the participants and were duly clarified by the speakers.</p>
<p class="img-with-caption"><img title="Dignitaries of the programme" class="img-responsive" style="" src="<?=PUBLIC_URL?>images/stock/patent_Programme_Hassan.jpg" alt="Dignitaries of the programme"/>Dignitaries of the programme</p>
<h3 id="IPR_Awareness_Programmes">IPR AWARENESS PROGRAMMES ORGANISED AT LOCAL ENGINEERING COLLEGES / INSTITUTES</h3>
<p>PIC conducted five half-day awareness programmes at five local engineering colleges. These programmes were aimed at bringing awareness among students (particularly final year students as they are to take their project work in their final semester) and faculty members. Each programme had a presentation on IPR, with focus on patent and copyright, followed by a question-answer session. The presentation included - general introduction about IPR, criteria for granting patent / copyright, validity, procedures for obtaining them, Patent Cooperation Treaty and some examples demonstrating the requirements (criteria). The duration of the programme was about 2 to 3 hours. The details of programmes organized are as follows:</p>
<ul>
	<li class="gap-above-small">At R V College of Engineering (RVCE), Bangalore, the programme was organized on 31st October 2008. The presentation was made by Mr J Abhayan, Head-Legal, BIOCON, Bangalore and was attended by 80 participants.</li>
	<li class="gap-above-small">At M S Ramaiah of Institute of Technology (MSRIT), Bangalore, the programme was organized on 18th November 2008. The presentation was made by Mr J Abhayan, Head-Legal, BIOCON, Bangalore and was attended by 70 participants.</li>
	<li class="gap-above-small">At Sir M Visvesvaraya Institute of Technology (SMVIT), Bangalore, the programme was organized on 28th Mar 2009. The presentation was made by Mr J Abhayan, Head-Legal, BIOCON, Bangalore and was attended by 134 participants.</li>
	<li class="gap-above-small">At Dayananda Sagar College of Engineering (DSCE), Bangalore, the programme was organized on 30th March 2009. The presentation was made by Mr Ravi Bhola, Partner, K &amp; S Partners, Bangalore and was attended by 49 participants.</li>
</ul>
<h3 id="SIET_Tumkur">Shridevi Institute of Engineering and Technology, Tumkur</h3>
<p>One-hour lecture on IPR was arranged on 6th Aug 2010, at Shridevi Institute of Engineering and Technology, Tumkur. This lecture was a part of Technical Session of Seminar and Exhibition, 33rd Series of Student Project Programme of KSCST. The lecture was given by Mr. S. T. Madhusudan, Senior Associate, K&amp;S Partners, an IPR law firm in Bangalore. The lecture was focussed on Patents and Patenting System in India and was attended by about 250 participants. The participants included faculty, students from various engineering colleges across the state.</p>
<p class="img-with-caption"><img title="IPR Workshop at SIET, Tumkur" class="img-responsive" style="" src="<?=PUBLIC_URL?>images/stock/SIET_Tumkur.jpg" alt="IPR Workshop at SIET, Tumkur"/>IPR Workshop at SIET, Tumkur</p>
<h3 id="BLDEA_Bijapur">BLDEA's College of Engineering and Technology, Bijapur</h3>
<p>This one-day workshop was organised, at Bijapur on 25th February 2011, with the association of BLDEA's College of Engineering and Technology, Bijapur and was arranged at Swami Vivekananada Seminar Hall of the College. The programme was inaugurated by Prof. B. G. Mulimani, Vice Chancellor, BLDE Univeristy, Bijapur. The function was presided by Dr. V. P. Huggi, Principal, BLDEA's College of Engineering and Technology, Bijapur. The speakers spoke how IPR can help in economic development of the country and also about importance of its awareness among academia and people from industry. Mr. Yashwant Dev Panwar, Principal Scientific Officer, PFC-TIFAC, New Delhi, spoke about the importance of IPR in present day economic scenario and also about efforts taken by TIFAC to strengthen IPR activity. He also informed about the participants about the technical and financial assistance provided by TIFAC, with specific reference to filing of patent applications.</p>
<p>There were three technical presentations - 'Introduction to IPR and Case Studies' by Mr. Yashawant Dev Panwar, PFC-TIFAC, 'Patenting System in India' by Mr. K. M. Vishwanathan, Former Deputy Controller of Patent and Design, Patent Office, Chennai and 'Copyrights and Trademarks: Their Importance in Industries' by Mr. Ameet Deshpande, Patent Attorney, R. K. Dewan and Co, Pune. The workshop was attended by about 140 participants. The participants included faculty, students from different departments of engineering college, polytechnic, medical and pharmacy colleges. There technical talks were followed by a question-answer session.</p>
<p class="img-with-caption"><img title="IPR Workshop at Bijapur" class="img-responsive" style="" src="<?=PUBLIC_URL?>images/stock/BLDEA_Bijapur.jpg" alt="IPR Workshop at Bijapur"/>IPR Workshop at Bijapur</p>
<h3 id="IISc_Bengaluru">Indian Institute of Science, Bangalore</h3>
<p>This half-day Seminar was jointly organized with IP Cell, Indian Institute of Science, Bangalore. The seminar was arranged at 9.30 am on 15th Nov 2011 at the Material Research Centre Auditorium, IISc. The welcome address was given by Dr. M. Prithviraj, Executive Secretary, KSCST. There were three speakers who spoke on technical aspects of IPR, with particular reference to patenting activity at IISc and commercialization of IPs. Mr. P. R. Dhanvantri proposed the vote of thanks.</p>
<p>There were three technical presentations - 'Introduction to IPR and Protection of IP in India' by Mr. J. Suresh, Patent Attorney, Thiru and Thiru Associates, Bangalore, 'Entrepreneurship : An Approach for Commercialisation' by Mr. Anand Talwai, Executive Director and Co-founder, NextWealth Entreprenuers Pvt Ltd, Bangalore and 'IP Protection and Management at IISc' by Ms. Brinda Varma, IP Executive, IP Cell, IISc. The workshop was attended by about 120 participants. The participants included students, research scholars and faculty from different departments at Indian Institute of Science.</p>
<h3 id="Ambedkar_Institute_of_Technology">Dr. Ambedkar Institute of Technology, Bangalore</h3>
<p>One half-day workshop was organized at Dr. Ambedkar Institute of Technology, Bangalore on 21st Mar 2012. In this workshop, Sri P. R. Dhanvantri, Consultant-PIC, KSCST, gave a presentation on Introduction to IPR, Patents and Patenting System in India. This workshop was attended by about 120 participants who included students and faculty members of the institute.</p>
<h3 id="Reva_Institute_of_Technology">Reva Institute of Technology and Management, Bangalore</h3>
<p>One half-day seminar was organized at Reva Institute of Technology, Bangalore on 15th Dec 2012. In this workshop, Sri P. R. Dhanvantri, Consultant-PIC, KSCST, gave a presentation on Introduction to IPR, Patents and Patenting System in India. This seminar was attended by about 110 participants who included UG and PG students, research scholars and faculty members of the institute.</p>
<h3 id="Manipal_Institute_of_Management">National Workshop at Manipal Institute of Management</h3>
<p>This two-day National Workshop on "Intellectual Property Rights (IPR) - Practices &amp; Management" was organized jointly with Manipal Institute of Management, at Manipal Institute of Management, Manipal, on 17-18 February 2012. The workshop was attended by about 230 participants. The participants included faculty, students and research scholars from various engineering, medical, science and law colleges and industry personnel.</p>
<p>Prof. Ramakrishna Chadaga, Director, Manipal Institute of Technology, welcomed the gathering. The programme was inaugurated by Shri T. Chandrashekhar, Director, Patent Facilitation Centre, TIFAC, New Delhi. The function was presided by Dr. H. Vinod Bhat, Pro-Vice Chancellor, Manipal University. The Guests of Honour were Shri Karthik Puttaih, CEO, Invntree, Bangalore and Dr. M. Prithviraj, Executive Secretary, KSCST. The speakers spoke how IPR can help in economic development of the country, importance of its awareness among academia and people from industry and present need for aggressively harnessing the innovation potential of the country. Dr. Suresh Prabhu, Coordinator, Manipal Institute of Technology, proposed the vote of thanks.</p>
<p>There were eleven technical presentations, spread over two days, covering a wide range of topics related to IPR and its practice and management in India. On the first day there were six sessions - "Introduction to IPR and Case Studies" by Mr. T. Chandrashekhar, Director, PFC, TIFAC, "Patenting relating to life forms like microorganisms, therapeutics and surgical Methods" by Mr. Durgesh Mukharya, K&amp;S Partners, Patent Attorneys, Bangalore, "Protection of Industrial Designs" by Mr. Vineed Abraham, Fox and Mandal, Patent Attorneys, Bangalore, "Patent facilities to academicians and research institutions" by Ms. Shikha Tejaswi, IPR Scientist, PFC, TIFAC, "Role of PIC in Karnataka" by Mr. P. R. Dhanvantri, KSCST, "Patenting System in India" by Mr. Sharana Gowda, Patent Examiner, Patent Office, Mumbai. This was followed by a question-answer session. The second day had five sessions - "IP strategies for academics" by Mr. T. Chandrashekhar, Director, PFC, TIFAC, "Model for IP Management and IP policies for academic institutions" by Dr. Siddarth Jabade, Professor, Mechanical Engineering and IP Coordinator, Vishwakarma Institute of Technology, Pune, "Patent search strategies and methodologies" by Ms. Shikha Tejaswi, IPR Scientist, PFC, TIFAC, "Copyright and Trademark protection" and "WTO &amp; IPR issues in TRIPS" by Mr. Abhayan Jawaharlal, Head, Legal, Biocon, Bangalore. Also there was a hands-on demonstration on patent search by PFC team.</p>
<section id="examples" class="examples-section">
	<div class="image-row">
		<div class="image-set">
			<a class="example-image-link" href="<?=PUBLIC_URL?>images/stock/Manipal1.jpg" data-lightbox="example-set" data-title="National Workshop at Manipal Institute of Management"><img class="example-image" src="<?=PUBLIC_URL?>images/stock/Manipal1.jpg" alt="National Workshop at Manipal Institute of Management"/></a>
			<a class="example-image-link" href="<?=PUBLIC_URL?>images/stock/Manipal2.jpg" data-lightbox="example-set" data-title="National Workshop at Manipal Institute of Management"><img class="example-image" src="<?=PUBLIC_URL?>images/stock/Manipal2.jpg" alt="National Workshop at Manipal Institute of Management"/></a>
		</div>
	</div>
</section>
<h3>IPR WORKSHOPS ORGANISED JOINTLY WITH KARNATATAKA COUNCIL FOR TECHNOLOGICAL UPGRADATION (KCTU)</h3>
<p>PIC organized three one-day IPR workshops at various District Industries Centres (DIC) in the state, jointly with Karnataka Council for Technological Upgradation (KCTU). District Industries Centres were also involved in organising the workshops. Each workshop had three or four technical sessions by patent professionals (patent attorneys, officials from PFC-TIFAC and patent offices). These technical sessions were followed by a question-answer session. The participants included faculty, students from various engineering and law colleges, polytechnics, advocates and people from industries and government departments.</p>
<h3 id="Patent_Workshop_at_Hubli">PATENT WORKSHOP AT HUBLI</h3>
<p>The Patent Workshop was organized at Conference Hall, North Karnataka Small Scale Industries Association (NKSSIA) with support from Technology Information, Forecasting and Assessment Council (TIFAC), Department of Science and Technology, Government of India, on 9th August 2007. This programme was jointly organised with Karnataka Council for Technology Upgradation (KCTU), a state government body also interested in promoting awareness about IPR, and was specially aimed at people from industries. The main objective of the meeting was to make technocrats, academics, people from industry aware of patents, laws related to patenting, relevant procedures and its implications in view of present scenario of globalization. Several people from industries located in Hubli-Dharwar industrial belt and neighbouring districts were invited to participate in this programme. About 60 persons from various institutions attended the programme. The participants included faculty, students from various colleges, people from industries and government departments.</p>
<p>The programme started with the introduction of dignitaries by Mr. N. Chandrasekhar, Managing Director, KCTU. He also gave a brief introduction of KCTU. A brief introduction of KSCST and Patent Information Cell at KSCST was given by Mr. P. R. Dhanvantri. The programme was inaugurated by Mr. Ashok Ladwa, President, North Karnataka Small Scale Industries Association (NKSSIA). The Chief Guest, Prof. M. I. Savadatti, former Vice-Chancellor, Mangalore University delivered the keynote address. In the keynote address, Prof. Savadatti mentioned the importance patents citing examples of Indian products like Basmati rice, turmeric etc. Mr. P. R. Dhanvantri, KSCST, proposed the vote of thanks.</p>
<p>The first technical session consisted of two lectures - "Introduction to IPR and Case Studies" by Mr. Y. D. Panwar, Scientist, PFC-TIFAC, New Delhi and "Patenting System in India" by Mr. Rakesh Kumar, Patent Office, Mumbai. Mr. Panwar spoke on different forms of IPRs with suitable examples, with specific reference to patents. Mr. Rakesh Kumar explained the present system of patenting in India and also gave necessary details on various steps involved in filing patents - like provisional and final specifications, patent examination, publication, opposition etc, time required for each of the steps, fees to be paid at different stages etc.</p>
<p>The second technical session also consisted of two lectures - "Novelty and Inventiveness in Patents" by Mr. Ravi Bhola, Patent Attorney, K &amp; S Partners, Bangalore and "Copyright Management" by Mr. Abhayan, Head Legal, Biocon India, Bangalore. Mr Bhola spoke on how novelty and inventiveness are essential for consideration for granting patents and also how novelty is established with the help of patent searches. Mr. Abhayan spoke extensively on what can be copyrighted, copyright registration, duration of copyright and many relevant issues regarding copyright management in present day context, citing many examples. Mr.Abhayan also spoke on Trademark registration and about infringement.</p>
<p>Further, these technical sessions were followed by question-answer session. Many questions related to technicalities of patents like patentability of innovations etc., and patenting procedures were posed by the participants and these were duly clarified by the speakers.</p>
<p>The vote of thanks was proposed by Mr. P. R. Dhanvantri, coordinator, KSCST.</p>
<p class="img-with-caption"><img title="Patent Workshop at Hubli" class="img-responsive" style="" src="<?=PUBLIC_URL?>images/stock/Patent_Workshop_at_Hubli.jpg" alt="Patent Workshop at Hubli"/>Dignitaries of the programme</p>
<h3 id="IPR_workshop_at_shimoga">IPR WORKSHOP AT DISTRICT INDUSTRIES CENTRE - SHIMOGA</h3>
<p>This workshop was jointly organised by Karnataka State Council for Science and Technology (KSCST) and Karnataka Council for Technology Upgradation (KCTU), in association with District Industries Centre, Shimoga, District Industries Association, Shimoga and Shimoga District Chamber of Commerce and Industry and was supported by Technology Information, Forecasting and Assessment Council (TIFAC), Department of Science and Technology, Government of India. The workshop was organized at Conference Hall, Hotel Mathura Paradise, Shimoga on 26th October 2007. The workshop was attended by about 125 participants who included faculty, students from various colleges, people from industries and government departments.</p>
<p>The programme started with the introduction of dignitaries by Shri P. R. Dhanvantri, PIC - KSCST. He also gave a brief introduction of KSCST and the Patent Information Cell at KSCST. The programme was inaugurated by Dr. P. Boregowda, KAS, Chief Executive Officer, Zilla Panchayat, Shimoga. In his inaugural speech, he spoke on importance of patenting in present day context. The chief guests were Shri P. Prabhudev, Joint Director, District Industries Centre, Shimoga, Shri K. S. Anantharamaiah, President, District Industries Association, Shimoga and Mr K. V. Vasantha Kumar, President, Shimoga District Chamber of Commerce &amp; Industry. They spoke about local innovations like Arecanut Skin Peeler and the possibility of patenting such innovations. Mr. P. R. Dhanvantri, KSCST, proposed the vote of thanks.</p>
<p>There were two technical sessions. The first session consisted of two lectures - "Introduction to IPR and Case Studies" by Mr. Y. D. Panwar, Scientist, PFC-TIFAC, New Delhi and "Patenting System in India" by Dr. A. T. Patre, Patent Office, Mumbai. Mr. Panwar spoke on different forms of IPRs with suitable examples, with specific reference to patents. Dr. A. T. Patre explained the present system of patenting in India and also gave necessary details on various steps involved in filing patents - like provisional and final specifications, patent examination, publication, opposition etc, time required for each of the steps, fees to be paid at different stages etc. The second session also consisted of two lectures - "Novelty and Inventiveness in Patents" by Mr. Raju Bhupathiraju, Patent Attorney, Fox and Mandal, Bangalore and "Trademark and Copyright Management" by Mr. Gaurav Miglani, Attorney, Worldwide Registration Bureau, New Delhi. Mr. Bhupathiraju spoke on how novelty and inventiveness are essential for consideration for granting patents and also how novelty is established with the help of patent searches. Mr. Miglani spoke extensively on what can be copyrighted, copyright registration, duration of copyright and many relevant issues regarding copyright management in present day context, citing many examples. Mr Miglani also spoke on Trademark registration and about infringement. Further, these sessions were followed by question-answer session during which questions related to technicalities of patents like patentability of innovations, patenting procedures etc were posed by the participants and were duly clarified by the speakers.</p>
<p class="img-with-caption"><img title="IPR workshop at shimoga" class="img-responsive" style="" src="<?=PUBLIC_URL?>images/stock/IPR_workshop_at_shimoga.jpg" alt="IPR workshop at shimoga"/>Inaugural of IPR Workshop at Shimoga</p>
<h3 id="IPR_workshop_at_Mysore">IPR WORKSHOP AT DISTRICT INDUSTRIES CENTRE - MYSORE</h3>
<p>This workshop was jointly organised by Karnataka State Council for Science and Technology (KSCST) and Karnataka Council for Technology Upgradation (KCTU), in association with District Industries Centre, Mysore, District Industries Association, Mysore and Mysore District Chamber of Commerce and Industry and was supported by Technology Information, Forecasting and Assessment Council (TIFAC), Department of Science and Technology, Government of India. The workshop was organized at Conference Hall, Hotel Guru Residency, Mysore, on 19th December 2007. The workshop was attended by about 90 participants who included faculty, students from various colleges, people from industries and government departments.</p>
<p>The programme started with the introduction of dignitaries by Shri M. Shivashankar, Joint Director, District Industries Centre, Mysore. The programme was inaugurated by Shri N. S. Channappa Gowda, IAS, Deputy Commissioner, Mysore District. In his inaugural speech, he spoke about the importance of IPR awareness in present day global economy and WTO regime. He said it is necessary that people from industry - whether small or large - should be aware of IPR protection. The chief guests were Shri H. N. Ramathirtha, President, Mysore Chamber of Commerce and Industry and Shri P. Vishwanath, President, Mysore Industries Association and ex-Mayor of Mysore City Corporation. They spoke about role of IPR in economic development of the nation and also about some of legal issues in IPR protection, citing specific examples from pharmaceutical industry. Shri N. Chandrasekhar, Managing Director, KCTU, proposed the vote of thanks.</p>
<p>There were two technical sessions. The first session consisted of two lectures - "Introduction to IPR and Case Studies" by Shri Y. D. Panwar, Scientist, PFC-TIFAC, New Delhi and "Patenting System in India" by Shri K. M. Vishwanathan, Deputy Controller of Patent and Designs, Patent Office, Chennai. Mr. Panwar spoke on different forms of IPRs with suitable examples, with specific reference to patents. Shri Vishwanathan explained the present system of patenting in India and also gave necessary details on various steps involved in filing patents - like provisional and final specifications, patent examination, publication, opposition, time requirement for each step, fees structure etc. The second session also consisted of two lectures - "Role of Patents in Industries and Universities" by Smt. Rachana Singh Puri, Chief Executive Officer, Xellect IP Solutions, Bangalore and "Copyright Management" by Shri A. J. Abhayan, Head Legal, Biocon, Bangalore. Smt. Rachana Singh Puri spoke on importance of patents in the economic development of the nation and also about mutual interactions between university and industry in respect of patent worthy product development. Shri Abhayan spoke extensively on criteria for copyright, registration, duration of copyright and many relevant issues regarding copyright management in present day context, citing many examples. Shri Abhayan also spoke on Trademark registration and about infringement. Further, these sessions were followed by question-answer session during which questions related to technicalities of patents like patentability of innovations, patenting procedures etc were posed by the participants and were duly clarified by the speakers.</p>
<p class="img-with-caption"><img title="IPR workshop at Mysore" class="img-responsive" style="" src="<?=PUBLIC_URL?>images/stock/IPR_workshop_at_Mysore.jpg" alt="IPR workshop at Mysore"/>Inaugural of IPR Workshop at Mysore</p>
<h3 id="IPR_workshop_at_Belgaum">IPR WORKSHOP AT DISTRICT INDUSTRIES CENTRE - BELGAUM</h3>
<p>This workshop was jointly organised by Karnataka State Council for Science and Technology (KSCST) and Karnataka Council for Technology Upgradation (KCTU), in association with District Industries Centre, Belgaum, Belgaum Small Scale Industries Association and KLES - STEP, Belgaum and sponsored by TIFAC, New Delhi. The workshop was organized at Silver Jubilee Hall, KLES College of Engineering and Technology, Belgaum, on 15th February 2008. The workshop was attended by about 203 participants who included faculty, students from various engineering, law and medical colleges, polytechnics, advocates and people from industries and government departments.</p>
<p>The programme started with the introduction of dignitaries by Shri M. Prabhu, Joint Director, District Industries Centre, Belgaum. Shri P. R. Dhanvantri, Nodal Officer, KSCST, gave introduction of activities of KSCST while Shri T. Siddanna, Deputy Director, DIC-Belgaum, spoke about KCTU. The programme was inaugurated by Shri Vinay Jathar, President, Belgaum Chamber of Commerce and Industry. The chief guests were Shri Subhash V. Balekundri, President, Belgaum Small Scale Industries Association and Shri S. C. Pilli, Prinicipal, KLES College of Engineering and Technology, Belgaum. They spoke about the importance of IPR awareness and its role in economic development of the nation, particularly in present day global economy and WTO regime. Prof. Ramesh Burbure, Director, KLES-STEP, proposed the proposed the vote of thanks.</p>
<p>There were four technical lectures on different topics related to IPR. Shri Y. D. Panwar, Scientist, PFC-TIFAC, New Delhi, introduced the concept of IPR, with some case studies. Shri Shashidhara, Examiner of Patents and Designs, Patent Office Chennai talked about "Patenting System in India". Mr. Ravi Bhola, Patent Attorney, K &amp; S Partners, Bangalore, explained the need for `Novelty and Inventiveness in Patents'. Shri A. J. Abhayan, Head Legal, BIOCON, Bangalore, spoke extensively on "Copyright Management". Further, these sessions were followed by question-answer session during which questions related to technicalities of IPR like patentability of innovations, novelty in patenting, patenting and copyrighting procedures etc were posed by the participants and were duly clarified by the speakers.</p>
<p class="img-with-caption"><img title="IPR workshop at Belgaum" class="img-responsive" style="" src="<?=PUBLIC_URL?>images/stock/IPR_workshop_at_Belgaum.jpg" alt="IPR workshop at Belgaum"/>Inaugural of IPR Workshop at Belgaum</p>
<h3 id="IPR_workshop_at_Mangalore">IPR WORKSHOP AT DISTRICT INDUSTRIES CENTRE - MANGALORE</h3>
<p>This workshop was jointly organised by Karnataka State Council for Science and Technology (KSCST) and Karnataka Council for Technology Upgradation (KCTU), in association with District Industries Centre, Mangalore, Kanara Chamber of Commerce and Industries, Mangalore and SDM College of Business Management, Mangalore and sponsored by TIFAC, New Delhi. The workshop was organized at the Auditorium of SDM College of Business Management, Mangalore on 20th March 2008. The workshop was attended by about 120 participants who included faculty, students from various engineering, law and medical colleges, polytechnics, advocates and people from industries and government departments.</p>
<p>The programme started with the introduction of dignitaries by Shri Srinivas Kamath, Vice-President, Kanara Chamber of Commerce. Shri P. R. Dhanvantri, Nodal Officer, KSCST, gave introduction of activities of KSCST while Shri S. G. Hegde, Joint Director, DIC-Mangalore, spoke about KCTU. Dr. K. Devaraj, Principal, SDM College of Business Management introduced the Chief Guest, Shri K. Lakshminarayana, General Manager (Projects), ONGC-MRPL, Mangalore. The programme was inaugurated by the Chief Guest. Shri K. Lakshminarayana and Shri Srinivas Kamath spoke about the importance of IPR awareness and its role in economic development of the nation, particularly in present day global economy and WTO regime. Shri G. G. Mohandas Prabhu, Hon. Secretary, Kanara Chamber of Commerce, proposed the proposed the vote of thanks.</p>
<p>There were four technical lectures on different topics related to IPR. Shri Surya Senthil, Patent Attorney, JUS Maxima Law Office, Chennai, introduced the concept of IPR, with some case studies. Dr. V. Rengaswamy, Asst Controller and Head, Patent Office, Chennai talked about "Patenting System in India". Shri Surya Senthil continued his talk further, explaining the need for `Novelty and Inventiveness in Patents'. Shri A. J. Abhayan, Head Legal, BIOCON, Bangalore, spoke extensively on "Copyright Management". Further, these sessions were followed by question-answer session during which questions related to technicalities of IPR like patentability of innovations, novelty in patenting, patenting and copyrighting procedures etc were posed by the participants and were duly clarified by the speakers.</p>
<p class="img-with-caption"><img title="IPR workshop at Mangalore" class="img-responsive" style="" src="<?=PUBLIC_URL?>images/stock/IPR_workshop_at_Mangalore.jpg" alt="IPR workshop at Mangalore"/>Inaugural of IPR Workshop at Mangalore</p>
